import type { Vehicle } from '@/lib/types';

export const vehicles: Vehicle[] = [
  // Two Wheelers
  {
    id: '1',
    brand: 'Honda',
    model: 'Activa 6G',
    type: 'Two Wheeler',
    engineCapacity: 109,
    mileage: 50,
    fuelType: 'Petrol',
    price: 75000,
    seatingCapacity: 2,
    imageId: 'scooter',
  },
  {
    id: '2',
    brand: 'Yamaha',
    model: 'MT-15',
    type: 'Two Wheeler',
    engineCapacity: 155,
    mileage: 48,
    fuelType: 'Petrol',
    price: 165000,
    seatingCapacity: 2,
    imageId: 'motorcycle',
  },
  {
    id: '3',
    brand: 'Bajaj',
    model: 'Pulsar NS200',
    type: 'Two Wheeler',
    engineCapacity: 199,
    mileage: 35,
    fuelType: 'Petrol',
    price: 140000,
    seatingCapacity: 2,
    imageId: 'motorcycle-2',
  },
  {
    id: '4',
    brand: 'TVS',
    model: 'Apache RTR 160',
    type: 'Two Wheeler',
    engineCapacity: 160,
    mileage: 45,
    fuelType: 'Petrol',
    price: 120000,
    seatingCapacity: 2,
    imageId: 'motorcycle-3',
  },

  // Three Wheelers
  {
    id: '5',
    brand: 'Bajaj',
    model: 'RE Compact',
    type: 'Three Wheeler',
    engineCapacity: 236,
    mileage: 40,
    fuelType: 'CNG',
    price: 230000,
    seatingCapacity: 4,
    imageId: 'auto-rickshaw',
  },
  {
    id: '6',
    brand: 'Piaggio',
    model: 'Ape City',
    type: 'Three Wheeler',
    engineCapacity: 200,
    mileage: 36,
    fuelType: 'Petrol',
    price: 210000,
    seatingCapacity: 4,
    imageId: 'auto-rickshaw-2',
  },

  // Four Wheelers
  {
    id: '7',
    brand: 'Tata',
    model: 'Nexon',
    type: 'Four Wheeler',
    engineCapacity: 1199,
    mileage: 17,
    fuelType: 'Petrol',
    price: 800000,
    seatingCapacity: 5,
    imageId: 'suv',
  },
  {
    id: '8',
    brand: 'Hyundai',
    model: 'Creta',
    type: 'Four Wheeler',
    engineCapacity: 1497,
    mileage: 17,
    fuelType: 'Petrol',
    price: 1100000,
    seatingCapacity: 5,
    imageId: 'suv-2',
  },
  {
    id: '9',
    brand: 'Maruti',
    model: 'Swift',
    type: 'Four Wheeler',
    engineCapacity: 1197,
    mileage: 22,
    fuelType: 'Petrol',
    price: 600000,
    seatingCapacity: 5,
    imageId: 'hatchback',
  },
  {
    id: '10',
    brand: 'Mahindra',
    model: 'Thar',
    type: 'Four Wheeler',
    engineCapacity: 2184,
    mileage: 15,
    fuelType: 'Diesel',
    price: 1400000,
    seatingCapacity: 4,
    imageId: 'suv-3',
  },
   {
    id: '11',
    brand: 'Tata',
    model: 'Nexon EV',
    type: 'Four Wheeler',
    engineCapacity: 0,
    mileage: 325,
    fuelType: 'Electric',
    price: 1500000,
    seatingCapacity: 5,
    imageId: 'suv-4',
  },

  // Six Wheelers
  {
    id: '12',
    brand: 'Tata Motors',
    model: 'Ultra T.7',
    type: 'Six Wheeler',
    engineCapacity: 2956,
    mileage: 10,
    fuelType: 'Diesel',
    price: 1500000,
    seatingCapacity: 3,
    loadCapacity: 4950,
    imageId: 'truck',
  },
  {
    id: '13',
    brand: 'Ashok Leyland',
    model: 'Ecomet 1615 HE',
    type: 'Six Wheeler',
    engineCapacity: 3839,
    mileage: 7,
    fuelType: 'Diesel',
    price: 2300000,
    seatingCapacity: 3,
    loadCapacity: 10800,
    imageId: 'truck-2',
  },
];

export const brands = [...new Set(vehicles.map((v) => v.brand))];
export const vehicleTypes = [...new Set(vehicles.map((v) => v.type))];
export const fuelTypes = [...new Set(vehicles.map((v) => v.fuelType))];
